services:
  - type: web
    name: gemini-web2api-server
    env: python
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    
    # Render'a Docker yerine doğrudan Python projesi kurmasını söylüyoruz
    buildCommand: "pip install -r requirements.txt"
    
    # Tüm dosyalar yerli yerinde olduğu için komutumuz artık kusursuz çalışacak
    startCommand: "cp /etc/secrets/config.json ./config.json && python gemini_web2api.py"
    
    envVars:
      - key: PORT
        value: "8081"
